import { SelectOption } from "@/types";

export const toursIncludesOption: SelectOption[] = [
  { value: "transportation", label: "Transporte" },
  { value: "meals", label: "Comidas" },
  { value: "drinks", label: "Bebidas" },
  { value: "guide", label: "Guía turístico" },
  { value: "entrance", label: "Entradas / Tickets" },
  { value: "equipment", label: "Equipo" },
  { value: "accommodation", label: "Alojamiento" },
  { value: "insurance", label: "Seguro" },
  { value: "photos", label: "Fotos" },
  { value: "pickup", label: "Recogida en hotel" },
  { value: "dropoff", label: "Regreso al hotel" },
  { value: "activities", label: "Actividades incluidas" },
  { value: "snacks", label: "Snacks" },
  { value: "souvenirs", label: "Recuerdo / Souvenir" },
  { value: "tips", label: "Propinas" },
  { value: "taxes", label: "Impuestos" },
  { value: "flights", label: "Vuelos" },
  { value: "visa", label: "Visado / Trámites migratorios" },
  { value: "personalExpenses", label: "Gastos personales" },
  { value: "extraMeals", label: "Comidas no mencionadas" },
  { value: "extraDrinks", label: "Bebidas no mencionadas" },
  { value: "optionalActivities", label: "Actividades opcionales" },
  { value: "insurance", label: "Seguro de viaje" },
  { value: "airportTransfers", label: "Traslados aeropuerto" },
  { value: "souvenirs", label: "Souvenirs" },
  { value: "photography", label: "Servicio de fotos / video" },
  { value: "equipmentRental", label: "Renta de equipo extra" },
];
